// examples/remote_work.do
//
// Replication of Table 1 of Battaglia, Christensen, Hansen & Sacher (2025),
// "Inference for Regression with Variables Generated by AI or Machine Learning"
// (arXiv:2402.15585), mirroring `ValidMLInference-main/remote_work.ipynb`.
//
// Dataset: ~16k San Diego job postings (NAICS 72) from Hansen et al. (2023),
// shipped as `data/remote_work_data.dta`. The variable `wfh_rwo` is an
// AI/ML-generated work-from-home indicator (DistilBERT), with the false-
// positive rate estimated at fpr=0.009 from a validation sample of size 1000.
//
// Run this file from the project root:
//     do "ValidMLInference-stata/examples/remote_work.do"
//
// Optional positional argument: `nguess` (number of multistart attempts for
// one_step_gmm). Defaults to 30 (Python notebook value). Pass a smaller value
// to smoke-test or to bound wall time:
//     do "ValidMLInference-stata/examples/remote_work.do" 5

clear all
version 17

args nguess_arg
local nguess = cond("`nguess_arg'" == "", 30, real("`nguess_arg'"))

// Adopath / mata library wiring. Adjust `proj` if running from elsewhere.
local proj "`c(pwd)'"
capture confirm file "`proj'/ValidMLInference-stata/src/ado/ols.ado"
if _rc {
    // Fallback when the do-file is launched from inside `examples/` or `src/`.
    local proj "C:/Users/loren/Dropbox/Replication_AIValidInference"
}
adopath ++ "`proj'/ValidMLInference-stata/src/ado"
adopath ++ "`proj'/ValidMLInference-stata/src/mata"
adopath ++ "`proj'/ValidMLInference-stata/src/help"
quietly mata: mata mlib index

use "`proj'/ValidMLInference-stata/data/remote_work_data.dta", clear
generate double log_salary = log(salary)

// Build fixed-effect dummies for the SOC occupation code and employment type.
// `ols`, `ols_bcm`, and `one_step_gmm` expect plain numeric varlists, so we
// pre-expand the categoricals here and drop the first level as the reference
// (matching patsy's default for `C(...)` with no explicit reference).
quietly encode soc_2021_2,           gen(soc2_id)
quietly encode employment_type_name, gen(empt_id)
quietly tabulate soc2_id, gen(_soc)
quietly tabulate empt_id, gen(_emp)
drop _soc1 _emp1
local fes _soc* _emp*

di _newline(2) as text "{hline 78}"
di as text "Remote Work and Wage Inequality (BCHS 2025 Table 1)"
di as text "{hline 78}"
di as text "one_step_gmm nguess = " as result `nguess' ///
    as text "  (upstream Python notebook uses 30)"

// ---------------------------------------------------------------------------
// Specification 1: log_salary ~ wfh_rwo (no fixed effects)
// ---------------------------------------------------------------------------

di _newline as text "{hline 78}"
di as text "Spec 1 -- No fixed effects"
di as text "{hline 78}"

di _newline as text ">>> OLS (HC0 robust SEs)"
ols log_salary wfh_rwo
estimates store rw_ols_noFE

di _newline as text ">>> ols_bcm  (fpr = 0.009, m = 1000)"
ols_bcm log_salary wfh_rwo, generated(wfh_rwo) fpr(0.009) m(1000)
estimates store rw_bcm_noFE

di _newline as text ">>> one_step_gmm (k = 3 mixture components, nguess = `nguess')"
local rw_gmm_noFE_ok 0
capture noisily one_step_gmm log_salary wfh_rwo, ///
    generated(wfh_rwo) k(3) nguess(`nguess') maxiter(300) seed(123)
if !_rc {
    estimates store rw_gmm_noFE
    local rw_gmm_noFE_ok 1
}
else {
    di as error "  one_step_gmm (no FE) failed; see note at the bottom of this file."
}

// ---------------------------------------------------------------------------
// Specification 2: log_salary ~ wfh_rwo + soc_2021_2 FE + employment_type FE
// ---------------------------------------------------------------------------

di _newline as text "{hline 78}"
di as text "Spec 2 -- With SOC-2021 and employment-type fixed effects"
di as text "{hline 78}"

di _newline as text ">>> OLS"
ols log_salary wfh_rwo `fes'
estimates store rw_ols_FE

di _newline as text ">>> ols_bcm"
ols_bcm log_salary wfh_rwo `fes', generated(wfh_rwo) fpr(0.009) m(1000)
estimates store rw_bcm_FE

di _newline as text ">>> one_step_gmm"
local rw_gmm_FE_ok 0
capture noisily one_step_gmm log_salary wfh_rwo `fes', ///
    generated(wfh_rwo) k(3) nguess(`nguess') maxiter(300) seed(123)
if !_rc {
    estimates store rw_gmm_FE
    local rw_gmm_FE_ok 1
}
else {
    di as error "  one_step_gmm (with FE) failed; see note at the bottom of this file."
}

// ---------------------------------------------------------------------------
// Summary table -- the wfh_rwo row for every spec, side by side.
// ---------------------------------------------------------------------------

di _newline(2) as text "{hline 78}"
di as text "Summary: coefficient on wfh_rwo across specifications"
di as text "{hline 78}"

local tbl_models rw_ols_noFE rw_bcm_noFE
if `rw_gmm_noFE_ok' local tbl_models `tbl_models' rw_gmm_noFE
local tbl_models `tbl_models' rw_ols_FE rw_bcm_FE
if `rw_gmm_FE_ok'   local tbl_models `tbl_models' rw_gmm_FE

estimates table `tbl_models', ///
    keep(wfh_rwo) b(%9.4f) se(%9.4f) ///
    title("Coefficient on wfh_rwo (log salary on AI-generated WFH indicator)")

// ---------------------------------------------------------------------------
// Note on one_step_gmm convergence on this dataset
// ---------------------------------------------------------------------------
// The wfh_rwo indicator is positive in only ~2.4% of the postings and the
// OLS residuals are heavy-tailed (skewness ~1.5, kurtosis ~7). Under these
// conditions, Mata's d0-BFGS finite-difference line search can step into a
// region where log(sigma) is extremely negative; even with the log-space
// likelihood, exp(-log_sigma) overflows and the objective is no longer
// finite, so the optimizer aborts.
//
// Python's jaxopt LBFGS handles this through autodiff gradients and a
// different line search, and produces the wfh_rwo coefficient of ~0.586
// (no FE) / ~0.519 (with FE) reported in BCHS 2025. A robust Mata-side
// remedy (e.g., a softplus reparameterisation of sigma or a bounded line
// search) is on the backlog -- see `AI_Collaboration/TODO.md`. The OLS and
// ols_bcm rows above are exact matches to the Python notebook output.
