// examples/topic_model_example.do
//
// Replication of Table 2 of Battaglia, Christensen, Hansen & Sacher (2025),
// "Inference for Regression with Variables Generated by AI or Machine Learning"
// (arXiv:2402.15585), mirroring `ValidMLInference-main/topic_model_example.ipynb`.
//
// Setting: CEO time-use survey from Bandiera et al. (2020). Each CEO has a
// "leadership" topic share estimated from a topic model. The regression is
// log employment on the leadership share and 11 controls, in both the full
// sample and a 10% subsample (where measurement error is larger).
//
// Run this file from the project root:
//     do "ValidMLInference-stata/examples/topic_model_example.do"

clear all
version 17

local proj "`c(pwd)'"
capture confirm file "`proj'/ValidMLInference-stata/src/ado/ols.ado"
if _rc {
    local proj "C:/Users/loren/Dropbox/Replication_AIValidInference"
}
adopath ++ "`proj'/ValidMLInference-stata/src/ado"
adopath ++ "`proj'/ValidMLInference-stata/src/mata"
adopath ++ "`proj'/ValidMLInference-stata/src/help"
quietly mata: mata mlib index

local data "`proj'/ValidMLInference-stata/data/topic_model"

use "`data'/estimation.dta", clear

// Load the topic-model matrices into Stata. Sets W_full, W_samp, B_full,
// B_samp, LDA, S.
qui do "`data'/load.do" "`data'"

// Compute kappa = mean(1/C_i) * sqrt(n_lda) from the LDA-fit data. The first
// column of LDA holds C_i for the full sample; the second for the subsample.
mata:
    LDA        = st_matrix("LDA")
    n_lda      = rows(LDA)
    st_numscalar("kappa_full", mean(1 :/ LDA[., 1]) * sqrt(n_lda))
    st_numscalar("kappa_samp", mean(1 :/ LDA[., 2]) * sqrt(n_lda))
end
local kappa_full = scalar(kappa_full)
local kappa_samp = scalar(kappa_samp)

di _newline(2) as text "{hline 78}"
di as text "CEO Time Use and Firm Performance (BCHS 2025 Table 2)"
di as text "{hline 78}"
di _newline as text "Sample size:       " as result _N
di as text         "Number of controls: " as result 11
di as text         "kappa (full):       " as result %9.4f `kappa_full'  ///
            "    [Python notebook reports 0.442]"
di as text         "kappa (subsample):  " as result %9.4f `kappa_samp'  ///
            "    [Python notebook reports 4.262]"

// Add the leadership-topic share as a column of the dataset so ols/ols_bca_topic
// can read it from there. We use the *full*-sample share for spec 1 and the
// *subsample* share for spec 2.
quietly {
    generate double topic_1 = .
    mata: st_store(., "topic_1", st_matrix("W_full")[., 1])
}

local Q q1 q2 q3 q4 q5 q6 q7 q8 q9 q10 q11

// ---------------------------------------------------------------------------
// Spec 1: full-sample topic shares
// ---------------------------------------------------------------------------

di _newline as text "{hline 78}"
di as text "Spec 1 -- Full sample"
di as text "{hline 78}"

di _newline as text ">>> OLS"
ols ly topic_1 `Q'
estimates store tm_ols_full

di _newline as text ">>> ols_bca_topic"
ols_bca_topic ly `Q', wmatrix(W_full) smatrix(S) bmatrix(B_full) k(`kappa_full')
estimates store tm_bca_full

// ---------------------------------------------------------------------------
// Spec 2: 10% subsample topic shares (noisier signal)
// ---------------------------------------------------------------------------

di _newline as text "{hline 78}"
di as text "Spec 2 -- 10% subsample (noisier topic estimates)"
di as text "{hline 78}"

quietly mata: st_store(., "topic_1", st_matrix("W_samp")[., 1])

di _newline as text ">>> OLS"
ols ly topic_1 `Q'
estimates store tm_ols_samp

di _newline as text ">>> ols_bca_topic"
ols_bca_topic ly `Q', wmatrix(W_samp) smatrix(S) bmatrix(B_samp) k(`kappa_samp')
estimates store tm_bca_samp

// ---------------------------------------------------------------------------
// Joint-estimation comparison row (read from MCMC draws shipped by the upstream
// package; the Stata port does not currently implement the joint estimator).
// ---------------------------------------------------------------------------

di _newline as text "{hline 78}"
di as text "Joint estimation (from shipped MCMC draws -- not re-fit here)"
di as text "{hline 78}"

quietly import delimited "`data'/gamma_draws.csv", asdouble varnames(nonames) clear
local sigma_y : di %9.6f r(sd_ly)
qui use "`data'/estimation.dta", clear
qui summarize ly
local sigma_y = r(sd)

quietly import delimited "`data'/gamma_draws.csv", asdouble varnames(nonames) clear
quietly generate double gamma_full = v1 * `sigma_y'
quietly generate double gamma_samp = v2 * `sigma_y'
quietly summarize gamma_full, detail
local gf_mean = r(mean)
local gf_lo   = r(p)         // placeholder; recompute via _pctile below
quietly _pctile gamma_full, p(2.5 97.5)
local gf_lo = r(r1)
local gf_hi = r(r2)
quietly summarize gamma_samp, detail
local gs_mean = r(mean)
quietly _pctile gamma_samp, p(2.5 97.5)
local gs_lo = r(r1)
local gs_hi = r(r2)

di as text "Full sample:   estimate = " as result %7.3f `gf_mean'  ///
            as text "  [" as result %7.3f `gf_lo' as text ", " ///
            as result %7.3f `gf_hi' as text "]"
di as text "10% subsample: estimate = " as result %7.3f `gs_mean'  ///
            as text "  [" as result %7.3f `gs_lo' as text ", " ///
            as result %7.3f `gs_hi' as text "]"

// ---------------------------------------------------------------------------
// Side-by-side summary of the leadership-topic coefficient
// ---------------------------------------------------------------------------

di _newline(2) as text "{hline 78}"
di as text "Summary: coefficient on topic_1 (leadership share)"
di as text "{hline 78}"

estimates table tm_ols_full tm_bca_full tm_ols_samp tm_bca_samp, ///
    keep(topic_1) b(%9.4f) se(%9.4f) ///
    title("Effect of leadership topic share on log employment")
